[tool.poetry]
name = "loto"
version = "0.1.0"
description = "Loto guessing"
authors = ["Marius"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
pandas = "^2.1.0"
sklearn = "^0.0.post10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
